name: Deploy to Heroku (Backend)

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/server-heroku.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add backend remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/vermeirekaat-message.git
      - name: Deploy backend to Heroku
        run: git push heroku-backend `git subtree split --prefix server main`:refs/heads/master --force